name: 'Publish Stable Release'

on:
  push:
    branches:
      - stable

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-stable:
    name: Version or publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn build

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          title: New release
          commit: New release
          version: yarn changeset version --snapshot # TODO: remove --snapshot once we're confident in the release process
          publish: yarn workspaces foreach -pvW --include @radix-ui/\\* --include radix-ui npm publish --tolerate-republish --access public --tag latest
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTOMATION_FROM_CHANCE }}
